 select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM("purchaseamount(usd)") as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customerid, 
    "purchaseamount(usd)"
FROM customer
WHERE discountapplied = 'Yes'
  AND "purchaseamount(usd)" >= (
      SELECT AVG("purchaseamount(usd)")
      FROM customer
  );


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    itempurchased,
    ROUND(AVG(reviewrating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY itempurchased
ORDER BY AVG(reviewrating) DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shippingtype,
    ROUND(AVG("purchaseamount(usd)"), 2) AS avg_purchase
FROM customer
WHERE shippingtype IN ('Standard', 'Express')
GROUP BY shippingtype;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT 
    subscriptionstatus,
    COUNT(customerid) AS total_customers,
    ROUND(AVG("purchaseamount(usd)"), 2) AS avg_spend,
    ROUND(SUM("purchaseamount(usd)"), 2) AS total_revenue
FROM customer
GROUP BY subscriptionstatus
ORDER BY total_revenue DESC, avg_spend DESC;

--between subscribers and non-subscribers.
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    itempurchased,
    ROUND(
        100.0 * SUM(CASE WHEN discountapplied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 
        2
    ) AS discount_rate
FROM customer
GROUP BY itempurchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customerid,
        previouspurchases,
        CASE 
            WHEN previouspurchases = 1 THEN 'New'
            WHEN previouspurchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        itempurchased,
        COUNT(customerid) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customerid) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, itempurchased
)
SELECT 
    category,
    itempurchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscriptionstatus,
    COUNT(customerid) AS repeat_buyers
FROM customer
WHERE previouspurchases > 5
GROUP BY subscriptionstatus;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    ROUND(SUM("purchaseamount(usd)"), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;



